num1 = input("Enter the first number: ")
print(" ")
num2 = input("Enter the second number: ")
print(" ")
num3 = input("Enter the third number: ")
print(" ")
num4 = input("Enter the first number: ")
print(" ")
num5 = input("Enter the second number: ")
print(" ")
num6 = input("Enter the third number: ")
print(" ")
print("Reverse order of %s %s %s %s %s %s --> %s %s %s %s %s %s"%(num1,num2,num3,num4,num5,num6,num6,num5,num4,num3,num2,num1))