full = float(input("Input Full Score = "))
real = float(input("Input Real Score = "))
print("----------------------------")
print("--- Calculate Percentage ---")
print("----------------------------")
print("Full Score: %.2f"%full)
print("Real Score: %.2f"%real)
print("----------------------------")
print("Percentage: %.2f%%"%(real/full*100))
print("----------------------------")